# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore myapp.csproj
    - name: Build Application
      run: dotnet build --no-restore myapp.csproj
    - name: Test Application
      run: dotnet test --no-build --verbosity normal myapp.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Dockeehub
      run: echo "Deploying to dockerhub registry..."
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: kiyotakamine/authz-service
        tags: kiyotakamine/authz-service:build-${{ github.run_number }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
